"""fix compositions table

Revision ID: 37de9b9c3cef
Revises: 991d3c0e0a49
Create Date: 2025-04-26 15:23:30.280719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37de9b9c3cef'
down_revision: Union[str, None] = '991d3c0e0a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('composers')
    # op.add_column('compositions', sa.Column('musician_id', sa.Integer(), nullable=True))
    # op.drop_constraint('compositions_composer_id_fkey', 'compositions', type_='foreignkey')
    # op.create_foreign_key(None, 'compositions', 'musicians', ['musician_id'], ['id'])
    # op.drop_column('compositions', 'composer_id')
    # op.add_column('musicians', sa.Column('full_name', sa.String(length=100), nullable=False))
    # op.add_column('musicians', sa.Column('death_date', sa.Date(), nullable=True))
    # op.add_column('musicians', sa.Column('nationality', sa.String(length=50), nullable=True))
    # op.add_column('musicians', sa.Column('bio', sa.Text(), nullable=True))
    # op.drop_column('musicians', 'instrument')
    # op.drop_column('musicians', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musicians', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('musicians', sa.Column('instrument', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('musicians', 'bio')
    op.drop_column('musicians', 'nationality')
    op.drop_column('musicians', 'death_date')
    op.drop_column('musicians', 'full_name')
    op.add_column('compositions', sa.Column('composer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'compositions', type_='foreignkey')
    op.create_foreign_key('compositions_composer_id_fkey', 'compositions', 'composers', ['composer_id'], ['id'])
    op.drop_column('compositions', 'musician_id')
    op.create_table('composers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('death_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='composers_pkey')
    )
    op.create_index('ix_composers_id', 'composers', ['id'], unique=False)
    # ### end Alembic commands ###
