"""create_composers_tables

Revision ID: 90c86603e8ee
Revises: 6ba046b48fa4
Create Date: 2025-04-26 15:40:29.388909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c86603e8ee'
down_revision: Union[str, None] = '6ba046b48fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('musician_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['musician_id'], ['musicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('ensemble_id', sa.Integer(), nullable=True),
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], ),
    sa.ForeignKeyConstraint(['ensemble_id'], ['ensembles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performances_id'), 'performances', ['id'], unique=False)
    op.add_column('musicians', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('musicians', sa.Column('death_date', sa.Date(), nullable=True))
    op.add_column('musicians', sa.Column('nationality', sa.String(length=50), nullable=True))
    op.add_column('musicians', sa.Column('bio', sa.Text(), nullable=True))
    op.drop_column('musicians', 'instrument')
    op.drop_column('musicians', 'name')
    op.create_foreign_key(None, 'record_performance', 'performances', ['performance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record_performance', type_='foreignkey')
    op.add_column('musicians', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('musicians', sa.Column('instrument', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('musicians', 'bio')
    op.drop_column('musicians', 'nationality')
    op.drop_column('musicians', 'death_date')
    op.drop_column('musicians', 'full_name')
    op.drop_index(op.f('ix_performances_id'), table_name='performances')
    op.drop_table('performances')
    op.drop_table('compositions')
    # ### end Alembic commands ###
