"""composition now links to ensemble

Revision ID: 931c046ecebe
Revises: f053244b31e3
Create Date: 2025-04-27 13:19:46.273917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931c046ecebe'
down_revision: Union[str, None] = 'f053244b31e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_performances',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('record_id', 'performance_id')
    )
    op.drop_table('record_performance')
    op.alter_column('labels', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('labels', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('records', 'catalog_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('records', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('records', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('records', 'wholesale_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('records', 'retail_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('records', 'label_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'label_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('records', 'retail_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('records', 'wholesale_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('records', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('records', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('records', 'catalog_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('labels', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('labels', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table('record_performance',
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], name='record_performance_performance_id_fkey'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name='record_performance_record_id_fkey'),
    sa.PrimaryKeyConstraint('record_id', 'performance_id', name='record_performance_pkey')
    )
    op.drop_table('record_performances')
    # ### end Alembic commands ###
