"""fix composers table

Revision ID: 991d3c0e0a49
Revises: 419976eb4149
Create Date: 2025-04-26 14:31:58.812451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991d3c0e0a49'
down_revision: Union[str, None] = '419976eb4149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composers_id'), 'composers', ['id'], unique=False)
    op.add_column('compositions', sa.Column('genre', sa.String(length=50), nullable=True))
    op.add_column('compositions', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('compositions', sa.Column('composer_id', sa.Integer(), nullable=True))
    op.alter_column('compositions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index('ix_compositions_id', table_name='compositions')
    op.create_foreign_key(None, 'compositions', 'composers', ['composer_id'], ['id'])
    op.drop_column('compositions', 'composer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compositions', sa.Column('composer', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'compositions', type_='foreignkey')
    op.create_index('ix_compositions_id', 'compositions', ['id'], unique=False)
    op.alter_column('compositions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('compositions', 'composer_id')
    op.drop_column('compositions', 'duration')
    op.drop_column('compositions', 'genre')
    op.drop_index(op.f('ix_composers_id'), table_name='composers')
    op.drop_table('composers')
    # ### end Alembic commands ###
