"""composition now links to ensemble

Revision ID: bbc67487123c
Revises: 90c86603e8ee
Create Date: 2025-04-27 12:23:15.619713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc67487123c'
down_revision: Union[str, None] = '90c86603e8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compositions', sa.Column('ensemble_id', sa.Integer(), nullable=True))
    op.drop_constraint('compositions_musician_id_fkey', 'compositions', type_='foreignkey')
    op.create_foreign_key(None, 'compositions', 'ensembles', ['ensemble_id'], ['id'])
    op.drop_column('compositions', 'musician_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compositions', sa.Column('musician_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'compositions', type_='foreignkey')
    op.create_foreign_key('compositions_musician_id_fkey', 'compositions', 'musicians', ['musician_id'], ['id'])
    op.drop_column('compositions', 'ensemble_id')
    # ### end Alembic commands ###
